"""Structured response validation for contributor plans."""

from dataclasses import dataclass
from typing import Any


@dataclass
class ContributionPlan:
    """The stable Phase 1 output contract."""

    issue_summary: str
    relevant_files: list[dict[str, str]]
    implementation_plan: list[str]
    tests: list[str]
    risks: list[str]

    @classmethod
    def from_dict(cls, value: Any) -> "ContributionPlan":
        if not isinstance(value, dict):
            raise ValueError("The model response must be a JSON object.")

        required = {
            "issue_summary",
            "relevant_files",
            "implementation_plan",
            "tests",
            "risks",
        }
        missing = required - value.keys()
        if missing:
            raise ValueError(f"Missing required fields: {', '.join(sorted(missing))}")

        issue_summary = value["issue_summary"]
        if not isinstance(issue_summary, str) or not issue_summary.strip():
            raise ValueError("issue_summary must be a non-empty string.")

        relevant_files = value["relevant_files"]
        if not isinstance(relevant_files, list):
            raise ValueError("relevant_files must be a list.")
        normalized_files: list[dict[str, str]] = []
        for item in relevant_files:
            if not isinstance(item, dict) or not isinstance(item.get("path"), str) or not isinstance(item.get("reason"), str):
                raise ValueError("Each relevant_files item needs string path and reason fields.")
            normalized_files.append({"path": item["path"], "reason": item["reason"]})

        lists: dict[str, list[str]] = {}
        for field in ("implementation_plan", "tests", "risks"):
            items = value[field]
            if not isinstance(items, list) or not all(isinstance(item, str) for item in items):
                raise ValueError(f"{field} must be a list of strings.")
            lists[field] = items

        return cls(issue_summary, normalized_files, lists["implementation_plan"], lists["tests"], lists["risks"])


def parse_plan(response: str) -> ContributionPlan:
    """Parse and validate JSON generated by the model."""

    import json

    try:
        value = json.loads(response)
    except json.JSONDecodeError as direct_error:
        # Some hosted Gemma responses include reasoning before the final JSON
        # object. Extract candidate objects, then apply the same strict schema
        # validation used for a direct JSON response.
        decoder = json.JSONDecoder()
        candidates = []
        for index, character in enumerate(response):
            if character != "{":
                continue
            try:
                candidate, _ = decoder.raw_decode(response[index:])
            except json.JSONDecodeError:
                continue
            if isinstance(candidate, dict):
                candidates.append(candidate)
        for candidate in reversed(candidates):
            try:
                return ContributionPlan.from_dict(candidate)
            except ValueError:
                continue
        raise ValueError(f"The model did not return valid JSON: {direct_error.msg}") from direct_error
    return ContributionPlan.from_dict(value)
