"""Structured response validation for contributor plans."""

from dataclasses import dataclass
from typing import Any


@dataclass
class ContributionPlan:
    """Machine-readable plan produced by the Contributor Simulator."""

    issue_understanding: dict[str, Any]
    relevant_files: list[dict[str, str]]
    implementation_approach: list[str]
    tests: list[dict[str, str]]
    risks_unknowns: list[str]
    contributor_checklist: list[str]

    @classmethod
    def from_dict(cls, value: Any) -> "ContributionPlan":
        if not isinstance(value, dict):
            raise ValueError("The model response must be a JSON object.")

        required = {
            "issue_understanding",
            "relevant_files",
            "implementation_approach",
            "tests",
            "risks_unknowns",
            "contributor_checklist",
        }
        missing = required - value.keys()
        if missing:
            raise ValueError(f"Missing required fields: {', '.join(sorted(missing))}")

        issue_understanding = value["issue_understanding"]
        if not isinstance(issue_understanding, dict):
            raise ValueError("issue_understanding must be an object.")
        for field in ("summary", "expected_behavior"):
            if not isinstance(issue_understanding.get(field), str) or not issue_understanding[field].strip():
                raise ValueError(f"issue_understanding.{field} must be a non-empty string.")
        acceptance_criteria = issue_understanding.get("acceptance_criteria")
        if not isinstance(acceptance_criteria, list) or not all(isinstance(item, str) for item in acceptance_criteria):
            raise ValueError("issue_understanding.acceptance_criteria must be a list of strings.")

        relevant_files = value["relevant_files"]
        if not isinstance(relevant_files, list):
            raise ValueError("relevant_files must be a list.")
        normalized_files: list[dict[str, str]] = []
        for item in relevant_files:
            if (
                not isinstance(item, dict)
                or not isinstance(item.get("path"), str)
                or not isinstance(item.get("reason"), str)
                or not isinstance(item.get("attention"), str)
            ):
                raise ValueError("Each relevant_files item needs string path, reason, and attention fields.")
            normalized_files.append(
                {"path": item["path"], "reason": item["reason"], "attention": item["attention"]}
            )

        implementation_approach = value["implementation_approach"]
        if not isinstance(implementation_approach, list) or not all(isinstance(item, str) for item in implementation_approach):
            raise ValueError("implementation_approach must be a list of strings.")

        normalized_tests: list[dict[str, str]] = []
        if not isinstance(value["tests"], list):
            raise ValueError("tests must be a list.")
        for item in value["tests"]:
            if not isinstance(item, dict) or not isinstance(item.get("path"), str) or not isinstance(item.get("purpose"), str) or not isinstance(item.get("change"), str):
                raise ValueError("Each tests item needs string path, purpose, and change fields.")
            normalized_tests.append({"path": item["path"], "purpose": item["purpose"], "change": item["change"]})

        lists: dict[str, list[str]] = {}
        for field in ("risks_unknowns", "contributor_checklist"):
            items = value[field]
            if not isinstance(items, list) or not all(isinstance(item, str) for item in items):
                raise ValueError(f"{field} must be a list of strings.")
            lists[field] = items

        return cls(
            issue_understanding,
            normalized_files,
            implementation_approach,
            normalized_tests,
            lists["risks_unknowns"],
            lists["contributor_checklist"],
        )


def parse_plan(response: str) -> ContributionPlan:
    """Parse and validate JSON generated by the model."""

    import json

    try:
        value = json.loads(response)
    except json.JSONDecodeError as direct_error:
        # Some hosted Gemma responses include reasoning before the final JSON
        # object. Extract candidate objects, then apply the same strict schema
        # validation used for a direct JSON response.
        decoder = json.JSONDecoder()
        candidates = []
        for index, character in enumerate(response):
            if character != "{":
                continue
            try:
                candidate, _ = decoder.raw_decode(response[index:])
            except json.JSONDecodeError:
                continue
            if isinstance(candidate, dict):
                candidates.append(candidate)
        for candidate in reversed(candidates):
            try:
                return ContributionPlan.from_dict(candidate)
            except ValueError:
                continue
        raise ValueError(f"The model did not return valid JSON: {direct_error.msg}") from direct_error
    return ContributionPlan.from_dict(value)
